In [42]:
from pathlib import Path
import pandas as pd

#Create a data folder for the files generated by this notebook.
from pathlib import Path
DATA_DIR = Path("../data") #./data Actual level ---- ../data 2 levels up
clean_movies_path = DATA_DIR / "clean_movies.csv"


# 0. Loading datasets imbd and links 
# Those two datasets are the conection between each movie and its information
movies_df = pd.read_csv(clean_movies_path)
movies_df.head(5)

,title,genres_list,overview,keywords,Cast_list,Director,vote_average,release_date,original_language,movieId
0,Inception,"['Action', 'Science Fiction', 'Adventure']","Cobb, a skilled thief who commits corporate es...","['rescue', 'mission', 'dream', 'airplane', 'pa...","['Tim Kelleher', 'Silvie Laguna', 'Natasha Bea...",Christopher Nolan,8.364,2010-07-15,en,79132
1,Interstellar,"['Adventure', 'Drama', 'Science Fiction']",The adventures of a group of explorers who mak...,"['rescue', 'future', 'spacecraft', 'race again...","['Jeff Hephner', 'William Devane', 'Elyes Gabe...",Christopher Nolan,8.417,2014-11-05,en,109487
2,The Dark Knight,"['Drama', 'Action', 'Crime', 'Thriller']",Batman raises the stakes in his war on crime. ...,"['joker', 'sadism', 'chaos', 'secret identity'...","['Tommy Lister Jr.', 'Edison Chen', 'Beatrice ...",Christopher Nolan,8.512,2008-07-16,en,58559
3,Avatar,"['Action', 'Adventure', 'Fantasy', 'Science Fi...","In the 22nd century, a paraplegic Marine is di...","['future', 'society', 'culture clash', 'space ...","['Carvon Futrell', 'Joel David Moore', 'Jon Cu...",James Cameron,7.573,2009-12-15,en,72998
4,The Avengers,"['Science Fiction', 'Action', 'Adventure']",When an unexpected enemy emerges and threatens...,"['new york city', 'superhero', 'shield', 'base...","['Haneyuri', 'Nako Mizusawa', 'Marin', 'Rikako...",Joss Whedon,7.710,2012-04-25,en,89745

In [54]:
##### Join elements in the case of list and not text, but this is not the case, this is just plain text

# def flatten_list(text):
#     if isinstance(text, list):
#         # Join elements with space 
#         return " ".join(text)
#     elif isinstance(text, str) and text.startswith("["):
#         # In the case that data come as strin, like in this case, but also will be solved with puntuaction cleaning
#         import ast
#         try:
#             actual_list = ast.literal_eval(text)
#             return " ".join(actual_list)
#         except:
#             return text
#     return text

# # Apply the function to columns with lists befeore create the combined_features
# cols_to_fix = ['genres_list', 'keywords', 'Cast_list']
# for col in cols_to_fix:
#     movies_df[col] = movies_df[col].apply(flatten_list)

# movies_df.head(5)

In [55]:
#For cleaning NLP GENRES is better to have it as a plain text, to make lematization, and vectorization 
# To used in the model is better as a list, but for cleaning (mostly in countVectorization or TfIdfVectorizar
# movies_df["genres_text"] = movies_df["genres_list"].apply(lambda x: " ".join(x).lower())

# movies_df.head(5)
# print(movies_df.iloc[0]) # One row as a serie
# print(movies_df.iloc[[0]]) ## One row as a df

# Print column and name of the column
# print(movies_df.columns[0])
# print(movies_df.iloc[:, 0])
# movies_df.iloc[:,len(movies_df.columns) - 1]

In [56]:
movies_df["combined_features"] = (
    movies_df["movieId"].astype(str) + " " +
    movies_df["title"] + " " +
    movies_df["genres_list"] + " " +
    movies_df["overview"].fillna("") + " " +
    movies_df["keywords"].fillna("") + " " +
    movies_df["Director"].fillna("") + " " +
    movies_df["Cast_list"].fillna("") + " " +
    movies_df["vote_average"].astype(str) + " " +
    movies_df["release_date"].fillna("")
)
movies_df.head(5)

,title,genres_list,overview,keywords,Cast_list,Director,vote_average,release_date,original_language,movieId,combined_features
0,Inception,Action Science Fiction Adventure,"Cobb, a skilled thief who commits corporate es...",rescue mission dream airplane paris france vir...,Tim Kelleher Silvie Laguna Natasha Beaumont Kr...,Christopher Nolan,8.364,2010-07-15,en,79132,79132 Inception Action Science Fiction Adventu...
1,Interstellar,Adventure Drama Science Fiction,The adventures of a group of explorers who mak...,rescue future spacecraft race against time art...,Jeff Hephner William Devane Elyes Gabel Topher...,Christopher Nolan,8.417,2014-11-05,en,109487,109487 Interstellar Adventure Drama Science Fi...
2,The Dark Knight,Drama Action Crime Thriller,Batman raises the stakes in his war on crime. ...,joker sadism chaos secret identity crime fight...,Tommy Lister Jr. Edison Chen Beatrice Rosen To...,Christopher Nolan,8.512,2008-07-16,en,58559,58559 The Dark Knight Drama Action Crime Thril...
3,Avatar,Action Adventure Fantasy Science Fiction,"In the 22nd century, a paraplegic Marine is di...",future society culture clash space travel spac...,Carvon Futrell Joel David Moore Jon Curry Laz ...,James Cameron,7.573,2009-12-15,en,72998,72998 Avatar Action Adventure Fantasy Science ...
4,The Avengers,Science Fiction Action Adventure,When an unexpected enemy emerges and threatens...,new york city superhero shield based on comic ...,Haneyuri Nako Mizusawa Marin Rikako Sakata Ai ...,Joss Whedon,7.710,2012-04-25,en,89745,89745 The Avengers Science Fiction Action Adve...

In [57]:
movies_df.to_csv("../data/movies_final.csv", index=False)